sudo: false
dist: trusty
language: python
python: '3.5'

install:
  - pip install markdown2

cache:
  directories:
    - build   # Reuse intermediate files.

script:
  - ./build.py local
  - ls -R ./build/